[build]
  publish = "."

[[headers]]
  for = "/__framer__/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/framer-assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/content/*"
  [headers.values]
    Cache-Control = "no-store"

[[headers]]
  for = "/admin/*"
  [headers.values]
    Cache-Control = "no-store"

[[headers]]
  for = "/tangram-*.js"
  [headers.values]
    Cache-Control = "no-store"

[[headers]]
  for = "/tangram-*.css"
  [headers.values]
    Cache-Control = "no-store"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
